name: CUDA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-18.04
    container: nvidia/cuda:10.2-devel-ubuntu18.04

    steps:
      - run: nvcc --version

      - name: Add wget
        run: apt-get update && apt-get install -y wget
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.5
      - run: cmake --version

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U numpy pybind11[global]

      - name: Configure cmake
        id: configure
        run: cmake . -B src/exoplanet_core/jax -DCMAKE_BUILD_TYPE=Release

      - name: Configure Error Processing
        if: ${{ failure() && steps.configure.outcome == 'failure' }}
        working-directory: ${{ env.build_dir }}
        run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi

      - name: Build everything else
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j `nproc`
        shell: bash -l {0}
