name: CUDA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-18.04
    container: nvidia/cuda:10.2-devel-ubuntu18.04

    steps:
      - name: Install wget
        run: apt-get update && apt-get install -y wget
        env:
          DEBIAN_FRONTEND: "noninteractive"

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.11

      - name: Get the version info for NVCC and CMake
        run: |
          nvcc --version
          cmake --version

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U numpy pybind11[global]

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compile the extension
        run: |
          cmake --build build --target install
          ls build
          ls src/exoplanet_core/jax
