name: CUDA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-18.04
    container: nvidia/cuda:10.2-devel-ubuntu18.04

    steps:
      - name: Install system dependencies
        run: apt-get update && apt-get install -y wget git

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.5

      - name: Get the version info for NVCC and CMake
        run: |
        nvcc --version
        cmake --version

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -U jax jaxlib==0.1.57+cuda102 -f https://storage.googleapis.com/jax-releases/jax_releases.html
          python -m pip install -U numpy pybind11[global]
          python -m pip install -e .[test]

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compile the extension
        run: |
          cmake --build build
          cp build/gpu_driver*.so src/exoplanet_core/jax/

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -v tests/jax
