name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest"]
        include:
          - session: test
            extras: "test"
            test-path: "tests"
          - session: test_comparison
            extras: "test,comparison"
            test-path: "tests/core_test.py"
          - session: test_pymc3
            extras: "test,pymc3"
            test-path: "tests/pymc3_test.py"
          - session: test_pymc
            extras: "test,pymc"
            test-path: "tests/pymc_test.py"
          - session: test_pymc_jax
            extras: "test,pymc,jax"
            test-path: "tests/pymc_jax_test.py"
          - session: test_jax
            extras: "test,jax"
            test-path: "tests/jax_test.py"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv pip install --system ".[${{ matrix.extras }}]"

      - name: Run tests
        run: python -m pytest -v ${{ matrix.test-path }}
