name: Wheels
on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Run a pre-release, testing the build"
        required: false
        type: boolean
        default: false

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "macos-12"
          - "macos-14"
          - "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: pypa/cibuildwheel@v2.19.1
      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build twine
      - name: Build sdist
        run: python -m build --sdist .
      - name: Check the sdist
        run: python -m twine check dist/*.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_pypi:
    environment:
      name: pypi
      url: https://pypi.org/p/exoplanet-core
    permissions:
      id-token: write
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@v1.9.0
